# Generated by Django 5.1.4 on 2026-09-02 19:54

import django.db.models.deletion
import django.utils.timezone
import rooms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=rooms.models.generate_room_code, max_length=8, unique=True)),
                ('host_name', models.CharField(max_length=50)),
                ('max_players', models.IntegerField(default=10)),
                ('total_rounds', models.IntegerField(default=3)),
                ('current_round_num', models.IntegerField(default=0)),
                ('phase', models.CharField(choices=[('LOBBY', 'Lobby'), ('WORD_SELECT', 'Selecting Word'), ('DRAWING', 'Drawing'), ('ROUND_END', 'Round Ended'), ('GAME_END', 'Game Ended')], default='LOBBY', max_length=20)),
                ('smart_ai_enabled', models.BooleanField(default=True)),
                ('roast_mode_enabled', models.BooleanField(default=True)),
                ('custom_theme', models.CharField(blank=True, default='', max_length=100)),
                ('game_mode', models.CharField(choices=[('classic', 'Classic'), ('speed', 'Speed Round'), ('team', 'Team Mode'), ('chain_draw', 'Chain Draw')], default='classic', max_length=20)),
                ('current_drawer_nickname', models.CharField(blank=True, default='', max_length=50)),
                ('current_word', models.CharField(blank=True, default='', max_length=100)),
                ('word_hint', models.CharField(blank=True, default='', max_length=100)),
                ('timer_start_ms', models.BigIntegerField(default=0)),
                ('timer_duration_sec', models.IntegerField(default=80)),
                ('turn_order', models.JSONField(default=list)),
                ('current_turn_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(default=1)),
                ('drawer_nickname', models.CharField(blank=True, default='', max_length=50)),
                ('word', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('is_flagged', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_nickname', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='rooms.round')),
            ],
        ),
        migrations.CreateModel(
            name='ChainDrawStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=1)),
                ('player_nickname', models.CharField(max_length=50)),
                ('step_type', models.CharField(default='draw', max_length=10)),
                ('word_to_draw', models.CharField(blank=True, default='', max_length=100)),
                ('guessed_word', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_draw_steps', to='rooms.room')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain_draw_steps', to='rooms.round')),
            ],
            options={
                'ordering': ['round', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='StrokeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.BigIntegerField(default=0)),
                ('player_nickname', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('stroke', 'Stroke'), ('clear', 'Clear'), ('undo', 'Undo')], default='stroke', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stroke_events', to='rooms.room')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stroke_events', to='rooms.round')),
            ],
            options={
                'ordering': ['sequence_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('category', models.CharField(default='general', max_length=50)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_words', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('is_host', models.BooleanField(default=False)),
                ('is_connected', models.BooleanField(default=True)),
                ('is_ai', models.BooleanField(default=False)),
                ('is_spectator', models.BooleanField(default=False)),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('score', models.IntegerField(default=0)),
                ('has_guessed', models.BooleanField(default=False)),
                ('guess_order', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='rooms.room')),
            ],
            options={
                'unique_together': {('room', 'nickname')},
            },
        ),
    ]
