STARTER_WORDS = [
    # Animals (Easy & Medium)
    {"word": "CAT", "difficulty": "easy", "category": "animals"},
    {"word": "DOG", "difficulty": "easy", "category": "animals"},
    {"word": "FISH", "difficulty": "easy", "category": "animals"},
    {"word": "BIRD", "difficulty": "easy", "category": "animals"},
    {"word": "DUCK", "difficulty": "easy", "category": "animals"},
    {"word": "FROG", "difficulty": "easy", "category": "animals"},
    {"word": "LION", "difficulty": "medium", "category": "animals"},
    {"word": "TIGER", "difficulty": "medium", "category": "animals"},
    {"word": "BEAR", "difficulty": "easy", "category": "animals"},
    {"word": "RABBIT", "difficulty": "medium", "category": "animals"},
    {"word": "ELEPHANT", "difficulty": "medium", "category": "animals"},
    {"word": "GIRAFFE", "difficulty": "medium", "category": "animals"},
    {"word": "MONKEY", "difficulty": "easy", "category": "animals"},
    {"word": "PENGUIN", "difficulty": "medium", "category": "animals"},
    {"word": "DOLPHIN", "difficulty": "medium", "category": "animals"},
    {"word": "SHARK", "difficulty": "medium", "category": "animals"},
    {"word": "TURTLE", "difficulty": "easy", "category": "animals"},
    {"word": "SNAKE", "difficulty": "easy", "category": "animals"},
    {"word": "OCTOPUS", "difficulty": "medium", "category": "animals"},
    {"word": "BUTTERFLY", "difficulty": "medium", "category": "animals"},
    {"word": "SPIDER", "difficulty": "easy", "category": "animals"},
    {"word": "KANGAROO", "difficulty": "hard", "category": "animals"},
    {"word": "CHAMELEON", "difficulty": "hard", "category": "animals"},
    {"word": "FLAMINGO", "difficulty": "hard", "category": "animals"},
    {"word": "OWL", "difficulty": "easy", "category": "animals"},

    # Objects & Everyday Things (Easy & Medium)
    {"word": "SUN", "difficulty": "easy", "category": "nature"},
    {"word": "MOON", "difficulty": "easy", "category": "nature"},
    {"word": "STAR", "difficulty": "easy", "category": "nature"},
    {"word": "TREE", "difficulty": "easy", "category": "nature"},
    {"word": "FLOWER", "difficulty": "easy", "category": "nature"},
    {"word": "CLOUD", "difficulty": "easy", "category": "nature"},
    {"word": "RAINBOW", "difficulty": "medium", "category": "nature"},
    {"word": "VOLCANO", "difficulty": "medium", "category": "nature"},
    {"word": "HOUSE", "difficulty": "easy", "category": "objects"},
    {"word": "CAR", "difficulty": "easy", "category": "objects"},
    {"word": "BUS", "difficulty": "easy", "category": "objects"},
    {"word": "AIRPLANE", "difficulty": "medium", "category": "objects"},
    {"word": "ROCKET", "difficulty": "medium", "category": "objects"},
    {"word": "BICYCLE", "difficulty": "medium", "category": "objects"},
    {"word": "SHIP", "difficulty": "medium", "category": "objects"},
    {"word": "CLOCK", "difficulty": "easy", "category": "objects"},
    {"word": "PHONE", "difficulty": "easy", "category": "objects"},
    {"word": "KEY", "difficulty": "easy", "category": "objects"},
    {"word": "BOOK", "difficulty": "easy", "category": "objects"},
    {"word": "COMPUTER", "difficulty": "medium", "category": "objects"},
    {"word": "CAMERA", "difficulty": "medium", "category": "objects"},
    {"word": "GUITAR", "difficulty": "medium", "category": "objects"},
    {"word": "PIANO", "difficulty": "medium", "category": "objects"},
    {"word": "UMBRELLA", "difficulty": "medium", "category": "objects"},
    {"word": "LAMP", "difficulty": "easy", "category": "objects"},
    {"word": "CANDLE", "difficulty": "easy", "category": "objects"},
    {"word": "BALLOON", "difficulty": "easy", "category": "objects"},

    # Food & Drinks
    {"word": "APPLE", "difficulty": "easy", "category": "food"},
    {"word": "BANANA", "difficulty": "easy", "category": "food"},
    {"word": "PIZZA", "difficulty": "easy", "category": "food"},
    {"word": "BURGER", "difficulty": "easy", "category": "food"},
    {"word": "ICECREAM", "difficulty": "easy", "category": "food"},
    {"word": "DONUT", "difficulty": "easy", "category": "food"},
    {"word": "CAKE", "difficulty": "easy", "category": "food"},
    {"word": "COOKIE", "difficulty": "easy", "category": "food"},
    {"word": "POPCORN", "difficulty": "medium", "category": "food"},
    {"word": "TACO", "difficulty": "medium", "category": "food"},
    {"word": "SUSHI", "difficulty": "medium", "category": "food"},
    {"word": "WATERMELON", "difficulty": "medium", "category": "food"},
    {"word": "PINEAPPLE", "difficulty": "medium", "category": "food"},
    {"word": "AVOCADO", "difficulty": "hard", "category": "food"},
    {"word": "BROCCOLI", "difficulty": "medium", "category": "food"},
    {"word": "CHEESE", "difficulty": "easy", "category": "food"},
    {"word": "FRIES", "difficulty": "easy", "category": "food"},

    # Clothing & Accessories
    {"word": "HAT", "difficulty": "easy", "category": "clothing"},
    {"word": "SHOE", "difficulty": "easy", "category": "clothing"},
    {"word": "SHIRT", "difficulty": "easy", "category": "clothing"},
    {"word": "PANTS", "difficulty": "easy", "category": "clothing"},
    {"word": "CROWN", "difficulty": "medium", "category": "clothing"},
    {"word": "GLASSES", "difficulty": "easy", "category": "clothing"},
    {"word": "WATCH", "difficulty": "medium", "category": "clothing"},
    {"word": "BACKPACK", "difficulty": "medium", "category": "clothing"},
    {"word": "RING", "difficulty": "easy", "category": "clothing"},

    # Places & Fantasy
    {"word": "CASTLE", "difficulty": "medium", "category": "places"},
    {"word": "PYRAMID", "difficulty": "medium", "category": "places"},
    {"word": "ISLAND", "difficulty": "medium", "category": "places"},
    {"word": "MOUNTAIN", "difficulty": "medium", "category": "places"},
    {"word": "BEACH", "difficulty": "easy", "category": "places"},
    {"word": "BRIDGE", "difficulty": "medium", "category": "places"},
    {"word": "DRAGON", "difficulty": "medium", "category": "fantasy"},
    {"word": "UNICORN", "difficulty": "medium", "category": "fantasy"},
    {"word": "WIZARD", "difficulty": "hard", "category": "fantasy"},
    {"word": "GHOST", "difficulty": "easy", "category": "fantasy"},
    {"word": "MONSTER", "difficulty": "medium", "category": "fantasy"},
    {"word": "ALIEN", "difficulty": "medium", "category": "fantasy"},
    {"word": "ROBOT", "difficulty": "medium", "category": "fantasy"},
    {"word": "PIRATE", "difficulty": "medium", "category": "fantasy"},
    {"word": "SUPERHERO", "difficulty": "hard", "category": "fantasy"},

    # Actions & Concepts (Hard)
    {"word": "DANCING", "difficulty": "hard", "category": "actions"},
    {"word": "RUNNING", "difficulty": "hard", "category": "actions"},
    {"word": "SLEEPING", "difficulty": "hard", "category": "actions"},
    {"word": "SWIMMING", "difficulty": "hard", "category": "actions"},
    {"word": "FISHING", "difficulty": "hard", "category": "actions"},
    {"word": "COOKING", "difficulty": "hard", "category": "actions"},
    {"word": "PAINTING", "difficulty": "hard", "category": "actions"},
    {"word": "SKATEBOARDING", "difficulty": "hard", "category": "actions"},
    {"word": "SNOWMAN", "difficulty": "easy", "category": "holiday"},
    {"word": "TREASURE", "difficulty": "medium", "category": "objects"},
    {"word": "TELESCOPE", "difficulty": "hard", "category": "objects"},
    {"word": "SUBMARINE", "difficulty": "hard", "category": "objects"},
    {"word": "HELICOPTER", "difficulty": "hard", "category": "objects"},
    {"word": "LIGHTNING", "difficulty": "medium", "category": "nature"},
    {"word": "TORNADO", "difficulty": "hard", "category": "nature"},
    {"word": "ECLIPSE", "difficulty": "hard", "category": "nature"},
    {"word": "SKELETON", "difficulty": "hard", "category": "fantasy"},
    {"word": "MUMMY", "difficulty": "medium", "category": "fantasy"},
    {"word": "VAMPIRE", "difficulty": "hard", "category": "fantasy"},
    {"word": "COMPASS", "difficulty": "hard", "category": "objects"},
    {"word": "MAGNET", "difficulty": "medium", "category": "objects"},
    {"word": "MICROSCOPE", "difficulty": "hard", "category": "objects"},
    {"word": "PARACHUTE", "difficulty": "hard", "category": "objects"},
    {"word": "WINDMILL", "difficulty": "hard", "category": "places"},
    {"word": "LIGHTHOUSE", "difficulty": "hard", "category": "places"},
    {"word": "STATUE", "difficulty": "hard", "category": "places"},
]
